# Numpy Exercise

1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

2. Write a NumPy program to reverse an array (the first element becomes the last).
Original array:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

3. Write a NumPy program to convert an array to a floating type.

Sample output:

Original array

[1, 2, 3, 4]
Array converted to a float type:

[ 1. 2. 3. 4.]

4. Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

5. From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match



In [1]:
import numpy as np
mat = np.arange(2,11).reshape(3,3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,3,9,10])
match = np.where(arr1 == arr2)
print(match)

(array([2], dtype=int64),)
