# Getting Started work with Numpy

In [2]:
# As you know that Numpy is the Library of python so before work with Numpy we have to import Numpy

import numpy as np

# np is just like a variable or handle we used np to call numpy functions


In [3]:
# For define an array in Numpy

In [4]:
x = np.array([1,3,5,7])

In [5]:
x

array([1, 3, 5, 7])

In [6]:
# Numpy give us some functions of generating arrays
# zeros(row , column): It generates the array wiith all elements 0
# ones(rows, columns): It generates the array with all elements 1
# empty(): It generates the array with random numbers

In [8]:
np.zeros((4,2)) #an Array of zeros with 4 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.empty((4,6))

array([[4.67296746e-307, 1.69121096e-306, 1.24610994e-306,
        1.33511018e-306, 1.33511969e-306, 6.23037996e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [7.56599807e-307, 6.89804132e-307, 1.78019082e-306,
        1.11261027e-306, 1.02360731e-306, 1.05700515e-307],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 3.22643519e-307, 9.79103798e-307]])

In [13]:
# we can also generate the array of the even numbers an odd numbers for this we use arange()

np.arange(0,20,2) #(starting value , ending value-1,diffrence)

# You know that the ending value is not included in array thats why I write value-1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
for i in range(0,20 , 2):
    print(i)

0
2
4
6
8
10
12
14
16
18
