## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1



In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:])

[1 2 3 4 5 6 7]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
print(arr[4:6])

[5 6]
[5 6]


## STEP
Use the step value to determine the step of the slicing:

Example
Return every other element from index 1 to index 5:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [16]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1 , 1:3])

[7 8]


In [17]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [18]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
print(arr[0:2, 1:3])

[[2 3]
 [7 8]]


In [21]:
arr[0:3,1:3]

array([[2, 3],
       [7, 8]])

In [22]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])