In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn import linear_model

In [6]:
df = pd.read_csv("homeprices.csv")

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
median = df.bedrooms.median()

In [15]:
df.fillna(4 , inplace=True)

In [16]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
reg = linear_model.LinearRegression()

In [22]:
reg

LinearRegression()

In [23]:
reg

LinearRegression()

In [24]:
reg.fit(df.drop("price" , axis = "columns") , df.price)

LinearRegression()

In [25]:
reg.intercept_

221323.00186540408

In [26]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [27]:
reg.predict([[3300 , 4 , 40]])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([555415.86424089])

In [28]:
reg.predict([[5000 , 3 , 25]])

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([771008.90409407])